### ISSUE TITLE
Linux下转换时崩溃

### ISSUE THREAD

**Issue by singer233** [studyzy/imewlconverter#138]
尝试转换搜狗的词库到rime时 程序崩溃
系统 : archlinux
使用命令 `dotnet ImeWlConverterC -i:scel /tmp/build/搜狗标准词库.scel  -o:rime ./rime.txt`
输出如下
```
转换开始...
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Studyzy.IMEWLConverter.IME.SougouPinyinScel.ReadScel(String path) in /home/appveyor/imewlconverter/src/ImeWlConverterCore/IME/SougouPinyinScel.cs:line 118
   at Studyzy.IMEWLConverter.IME.SougouPinyinScel.Import(String path) in /home/appveyor/imewlconverter/src/ImeWlConverterCore/IME/SougouPinyinScel.cs:line 37
   at Studyzy.IMEWLConverter.MainBody.Convert(IList`1 filePathes) in /home/appveyor/imewlconverter/src/ImeWlConverterCore/MainBody.cs:line 207
   at Studyzy.IMEWLConverter.ConsoleRun.Run() in /home/appveyor/imewlconverter/src/ImeWlConverterCore/ConsoleRun.cs:line 124
   at Studyzy.IMEWLConverter.Program.Main(String[] args) in /home/appveyor/imewlconverter/src/ImeWlConverterCmd/Program.cs:line 18
已放弃 (核心已转储)
'''

**Comment by studyzy** [comment]
无法重现这个现象，怀疑是词库scel的格式问题。麻烦将您的搜狗标准词库.scel发给我一下，我本地调试看看。

**Comment by singer233** [comment]
换了一台电脑，重新下了一个词库就好了，怀疑可能是原先电脑的aria2导致文件损坏，谢谢帮助。
