### ISSUE TITLE
gbroad 的方法是不是忘记引入了?

### ISSUE THREAD

**Issue by JackyCZJ** [studyzy/imewlconverter#150]
```
dotnet ImeWlConverterCmd.dll -i:scel ../xxx.scel  -o:gboard ./*                                           
转换开始...
10:45:19	开始生成词频...
10:45:19	开始生成目标编码...
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at Studyzy.IMEWLConverter.IME.Gboard.get_Encoding() in /home/appveyor/imewlconverter/src/ImeWlConverterCore/IME/Gboard.cs:line 98
   at Studyzy.IMEWLConverter.ConsoleRun.Run() in /home/appveyor/imewlconverter/src/ImeWlConverterCore/ConsoleRun.cs:line 125
   at Studyzy.IMEWLConverter.Program.Main(String[] args) in /home/appveyor/imewlconverter/src/ImeWlConverterCmd/Program.cs:line 18
[1]    86179 abort      dotnet ImeWlConverterCmd.dll -i:scel ../xxx.sce
```
平台是macOS  , 不过应该和平台没有啥关系，转ggpy是没有问题的，具体报错的是这一行：
https://github.com/studyzy/imewlconverter/blob/1f5dee3b5ca646ae43f98a424ce3449f9c8be328/src/ImeWlConverterCore/IME/Gboard.cs#L98

**Comment by Poseiden** [comment]
这个问题修复了吗？

<img width="938" alt="image" src="https://user-images.githubusercontent.com/10356133/179401783-35b68944-3b00-4e25-a835-0ee135aa4350.png">
