### ISSUE TITLE
转换搜狗词库时候出现了错误 数组维度超过了

### ISSUE THREAD

**Issue by cusber** [studyzy/imewlconverter#151]
在运行程序的时候，出现了outof memory错误。并且实际内存只用了1g。
直接编译源代码，程序出现错误数组维度超过限制。

麻烦帮忙看一下。非常感谢。

链接是词库
链接: https://pan.baidu.com/s/1_S04PhA9-f37jILtU-60FQ 提取码: 2b4f

**Comment by cusber** [comment]
System.OutOfMemoryException
  HResult=0x8007000E
  Message=数组维度超过了支持的范围。
  Source=深蓝词库转换
  StackTrace:
   at Studyzy.IMEWLConverter.MainForm.backgroundWorker1_DoWork(Object sender, DoWorkEventArgs e) in D:\TMP\imewlconverter-master\src\IME WL Converter Win\Forms\MainForm.cs:line 535
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by cusber** [comment]
个人测试了一下，应该是和版本有关。我用的是搜狗7.9版本，用最新版的就没问题的。原因不明，非常感谢开发组。
