### ISSUE TITLE
mac下转换异常 doesn't support GBK，GB2312

### ISSUE THREAD

**Issue by QiLinJane** [studyzy/imewlconverter#154]
**问题:** 

与前 closed issue [mac下转换异常 doesn't support GBK，GB2312 · Issue #84 · studyzy/imewlconverter](https://github.com/studyzy/imewlconverter/issues/84) 问题同，issue显示开发者已经修复bug, 为什么我又遇到同问题？

**环境**
- macOS 10.12.6
- .NET Core 2.2
- [Release imewlconverter v2.5 · studyzy/imewlconverter](https://github.com/studyzy/imewlconverter/releases/tag/v2.5)

**配置**
完全按照[Release imewlconverter v2.5 · studyzy/imewlconverter](https://github.com/studyzy/imewlconverter/releases/tag/v2.5)
的步骤配置，结果报错

**报错**
```
转换开始...
13:06:21
13:06:21	开始生成词频...
'GBK' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name Your system doesn't support GBK, try to use GB2312.

Unhandled Exception: System.ArgumentException: 'GB2312' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at Studyzy.IMEWLConverter.IME.GooglePinyin.get_Encoding() in /home/pallet/imewlconverter/src/ImeWlConverterCore/IME/GooglePinyin.cs:line 55
   at Studyzy.IMEWLConverter.ConsoleRun.Run() in /home/pallet/imewlconverter/src/ImeWlConverterCore/ConsoleRun.cs:line 125
   at Studyzy.IMEWLConverter.Program.Main(String[] args) in /home/pallet/imewlconverter/src/ImeWlConverterCmd/Program.cs:line 17
Abort trap: 6
appledeMacBook-Pro-2:publish apple$ dotnet ImeWlConverterCmd.dll -i:scel ./test.scel -o:ggpy ./ggpy.txt
```
**查历史issue**
发现与[mac下转换异常 doesn't support GBK，GB2312 · Issue #84 · studyzy/imewlconverter](https://github.com/studyzy/imewlconverter/issues/84)同，

但不知如何解决？

**Comment by studyzy** [comment]
英文Mac系统吗？实在无法理解怎么会不支持GB2312，无法重现。
