### ISSUE TITLE
[Bug] [Win11] 本软件导出的 微软拼音自学习词库 导入失败

### ISSUE THREAD

**Issue by Ethkuil** [studyzy/imewlconverter#265]
> 背景：从搜狗拼音输入法迁移到微软拼音输入法。

导入时的报错：`Inport: failed (incorrect file format or damaged file)`.

个人猜测应该是微软那边改编码格式了？勾了兼容性选项依旧不行。

不过幸运的是，尝试导出为 微软拼音用户定义词库 就导入成功了，并验证了确实导入成功了。

但也有代价——`User defined phrases` 页面要加载很久很久才能打开……（我一开始还以为坏掉了呢）

**Comment by Ethkuil** [comment]
以“用户定义”的方式导入似乎还是有些难用，少敲哪怕一个字母都不会列到候选里，体验有点差。

**Comment by nopdan** [comment]
已解决。我还在重构我自己的转换工具，没精力给这项目提交 pr，先用这 ci 构建的吧。

https://github.com/nopdan/rose/actions/runs/5953294127

**Comment by Ethkuil** [comment]
> 已解决。我还在重构我自己的转换工具，没精力给这项目提交 pr（况且这作者好久没看pr了，合并要等到猴年马月），先用这 ci 构建的吧。
> 
> [nopdan/rose/actions/runs/5953294127](https://github.com/nopdan/rose/actions/runs/5953294127)

目标输出为「微软拼音自学习词汇」，以「搜狗拼音备份词库」为输入转换失败，打印信息：

```
输入词库: ./...bin
词库格式: 搜狗拼音备份.bin sgbin
panic: runtime error: index out of range [7] with length 4

goroutine 1 [running]:
encoding/binary.littleEndian.Uint64(...)
        /opt/hostedtoolcache/go/1.21.0/x64/src/encoding/binary/binary.go:102
github.com/nopdan/ku.BytesToInt(...)
        /home/runner/go/pkg/mod/github.com/nopdan/ku@v0.3.4/binary.go:9
github.com/nopdan/rose/pkg/rose.(*SogouBin).ParseOld(0xc0020b19d0)
        /home/runner/work/rose/rose/pkg/rose/sogou_bin.go:128 +0xa95
github.com/nopdan/rose/pkg/rose.(*SogouBin).Parse(0xc0020b19d0)
        /home/runner/work/rose/rose/pkg/rose/sogou_pinyin.go:30 +0x513
github.com/nopdan/rose/pkg/rose.FParse({0xc000016168, 0x12}, {0x95b9e0, 0xc0020b19d0})
        /home/runner/work/rose/rose/pkg/rose/rose.go:21 +0x4f
github.com/nopdan/rose/pkg/rose.Parse({0xc000016168, 0x12}, {0xc00000a130?, 0x3?})
        /home/runner/work/rose/rose/pkg/rose/rose.go:15 +0x3a
main.convert({0xc000016168, 0x12}, {0xc00000a150, 0x9}, {0xc00000a130, 0x5}, {0xc00000a136, 0x3})
        /home/runner/work/rose/rose/main.go:65 +0x1d6
main.main()
        /home/runner/work/rose/rose/main.go:57 +0x2ab
```

转而以「搜狗拼音」txt格式为输入（bin 转 txt 是之前用深蓝转的），转换成功，且成功导入微软拼音输入法。

**Comment by Ethkuil** [comment]
果然还是自学习词库的使用体验好，现在首字母也能出那些词了，用起来舒服多了。现在不用惦记搜狗拼音了。
