### ISSUE TITLE
搜狗系统词库转换出错

### ISSUE THREAD

**Issue by xzqbetter** [studyzy/imewlconverter#278]
是不是还不支持搜狗系统词库的转换，用了 3.0 版本的报错
```shell
词库（sgim_sys_mac.bin）处理出现异常：
	Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
转换完成,共转换0个
```
换了 #250 给的新包，也报错了
```shell
Process terminated. Assertion failed.
   at Studyzy.IMEWLConverter.IME.SougouPinyinBinFromPython.InitialiseUserDict(FileStream fs, UInt32& checksum) in /Users/Liam/Documents/git-dev/dotnet/imewlconverter/src/ImeWlConverterCore/IME/SougouPinyinBinFromPython.cs:line 113
   at Studyzy.IMEWLConverter.IME.SougouPinyinBinFromPython.Import(String path) in /Users/Liam/Documents/git-dev/dotnet/imewlconverter/src/ImeWlConverterCore/IME/SougouPinyinBinFromPython.cs:line 45
   at Studyzy.IMEWLConverter.MainBody.Convert(IList`1 filePathes) in /Users/Liam/Documents/git-dev/dotnet/imewlconverter/src/ImeWlConverterCore/MainBody.cs:line 242
   at Studyzy.IMEWLConverter.ConsoleRun.Run() in /Users/Liam/Documents/git-dev/dotnet/imewlconverter/src/ImeWlConverterCore/ConsoleRun.cs:line 141
   at Studyzy.IMEWLConverter.Program.Main(String[] args) in /Users/Liam/Documents/git-dev/dotnet/imewlconverter/src/ImeWlConverterCmd/Program.cs:line 34
zsh: abort      dotnet ./ImeWlConverterCmd.dll -i:sgpybin ./sgim_sys_mac.bin -o:sgpy 
```
搜狗版本：mac 6.14.1
命令行：
```shell
dotnet ./ImeWlConverterCmd.dll -i:sgpybin ./sgim_sys.bin -o:sgpy ./sougou.txt
```

**Comment by Azeril** [comment]
确实 挺奇怪的... 换了搜狗输入法版本（6.14 换到 6.10） 换了其它 iuuse 提供的新版本转换器 命令行转换显示成功 但数据条目为 0.
