### ISSUE TITLE
Something wrong about GBK in Linux

### ISSUE THREAD

**Issue by Jinzhengxu** [studyzy/imewlconverter#76]
### when run the imewlconverter
```bash
jason@jason-ThinkPad-X1-Carbon-6th:~/Downloads/google/publish$ dotnet ImeWlConverterCmd.dll -i:scel ../linux少量术语.scel -o:ggpy ./linux少量术语.txt
转换开始...

Unhandled Exception: System.ArgumentException: 'GBK' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at Studyzy.IMEWLConverter.IME.GooglePinyin.get_Encoding() in /Users/studyzy/Downloads/imewlconverter/ImeWlConverterCmd/IME/GooglePinyin.cs:line 46
   at Studyzy.IMEWLConverter.ConsoleRun.Run() in /Users/studyzy/Downloads/imewlconverter/ImeWlConverterCmd/ConsoleRun.cs:line 115
   at Studyzy.IMEWLConverter.Program.Main(String[] args) in /Users/studyzy/Downloads/imewlconverter/ImeWlConverterCmd/Program.cs:line 15
Aborted (core dumped)
```
#### the environment
```bash
Ubuntu 18.04
```

**Comment by dccmmtop** [comment]
linux 中 如何只输出词汇，而不含词频和拼音

**Comment by studyzy** [comment]
dotnet ImeWlConverterCmd.dll -i:scel ./bj.scel -o:word ./word.txt
