### ISSUE TITLE
mac中将搜狗bin词库转换为自定义txt的时候报Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by shaguagadzad** [studyzy/imewlconverter#93]
是在macOS上用转换mac上的搜狗输入法生成的bin，具体terminal log如下：

dotnet ImeWlConverterCmd.dll -i:sgpybin ./20190614.bin -o:self ./sg.txt "-f:213, nyyn" -c:./code.txt
转换开始...
14:42:01	开始生成词频...
14:42:01	生成词频：155450/230616
14:42:01	开始生成目标编码...
14:42:04	生成目标编码：26957/230616
14:42:07	生成目标编码：54237/230616
14:42:10	生成目标编码：81516/230616
14:42:13	生成目标编码：108915/230616
14:42:16	生成目标编码：136160/230616
14:42:19	生成目标编码：163562/230616
14:42:22	生成目标编码：191016/230616
14:42:25	生成目标编码：218040/230616

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Studyzy.IMEWLConverter.Helpers.UserCodingHelper.GetCodingDict(String filePath, Encoding encoding) in D:\Documents\GitHub\imewlconverter\src\ImeWlConverterCore\Helpers\UserCodingHelper.cs:line 47
   at Studyzy.IMEWLConverter.IME.SelfDefining.Prepare() in D:\Documents\GitHub\imewlconverter\src\ImeWlConverterCore\IME\SelfDefining.cs:line 25
   at Studyzy.IMEWLConverter.IME.SelfDefining.Export(WordLibraryList wlList) in D:\Documents\GitHub\imewlconverter\src\ImeWlConverterCore\IME\SelfDefining.cs:line 55
   at Studyzy.IMEWLConverter.MainBody.Convert(IList`1 filePathes) in D:\Documents\GitHub\imewlconverter\src\ImeWlConverterCore\MainBody.cs:line 239
   at Studyzy.IMEWLConverter.ConsoleRun.Run() in D:\Documents\GitHub\imewlconverter\src\ImeWlConverterCore\ConsoleRun.cs:line 124
   at Studyzy.IMEWLConverter.Program.Main(String[] args) in D:\Documents\GitHub\imewlconverter\src\ImeWlConverterCmd\Program.cs:line 17
Abort trap: 6

code.txt是用教程里面的「“汉字<Tab键>编码”每行一个。」

麻烦看一下是什么问题？

**Comment by AnLuoRidge** [comment]
我在 macOS 上也有相同的问题：

**环境**
dotnet-sdk-2.2.401-osx-x64

**测试文件内容：**
表面(biao|mian) 60007
表皮(biao|pi) 55000

`dotnet ./ImeWlConverterCmd.dll -i:bdpy ./test-bdpy -o:word ./word.txt`
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Studyzy.IMEWLConverter.IME.BaiduPinyin.ImportLine(String line) in D:\Documents\GitHub\imewlconverter\src\ImeWlConverterCore\IME\BaiduPinyin.cs:line 40
   at Studyzy.IMEWLConverter.IME.BaiduPinyin.ImportText(String str) in D:\Documents\GitHub\imewlconverter\src\ImeWlConverterCore\IME\BaiduPinyin.cs:line 32
   at Studyzy.IMEWLConverter.MainBody.Convert(IList`1 filePathes) in D:\Documents\GitHub\imewlconverter\src\ImeWlConverterCore\MainBody.cs:line 209
   at Studyzy.IMEWLConverter.ConsoleRun.Run() in D:\Documents\GitHub\imewlconverter\src\ImeWlConverterCore\ConsoleRun.cs:line 124
   at Studyzy.IMEWLConverter.Program.Main(String[] args) in D:\Documents\GitHub\imewlconverter\src\ImeWlConverterCmd\Program.cs:line 17
Abort trap: 6

**Comment by studyzy** [comment]
v2.7已增加异常检查
